const articles = [
    {
        id: "parabola-normal-line",
        title_ja: "放物線の法線に関するシンプルで興味深い問題",
        title_en: "Simple and Interesting Problems on Normals to Parabolas",
        author: "Yusei Fujii",
        date: "2025-07-29",
        abstract_ja: "放物線の法線に関する、直感的でありながら一筋縄ではいかない問題を解説。1問目は、放物線とその法線弦により囲まれた領域に関する最小値を議論する。シンプルな問題設定でありながら、高次関数の増減の評価、相加平均・相乗平均の関係、傘型近似、第一種オイラー積分、積の微分法などの様々な手法が必要になる点が興味深い。2問目は、放物線へ1点から引かれた3本の法線について分析する。この問題は、放物線の縮閉線との関連や、法線の足が原点と同一円周上にあるという性質が美しい。いずれも高校数学の範囲内での解説を試みた。",
        abstract_en: "This article explains intuitive yet challenging problems concerning the normals of a parabola. The first problem discusses the minimum value of the area enclosed by a parabola and its normal chord. Despite its simple setup, the problem is intriguing as it requires various techniques, such as evaluating the monotonicity of higher-degree functions, AM-GM inequality, umbrella approximation, Euler's integral of the first kind, and the product rule for differentiation. The second problem analyzes three normals drawn from a single point to a parabola. This problem is fascinating due to its connection with the parabola's evolute and the elegant property that the feet of the normals lie on the same circle as the origin. Both problems are explained within the scope of high school mathematics.",
        type_ja: "問題と解答",
        type_en: "Problem and Solution",
        lang_ja: "日本語",
        lang2_ja: "英語",
        lang_en: "Japanese",
        lang2_en: "English",
        pdf_path_ja: "Yusei Fujii - Normal Line of Parabola (JP).pdf",
        pdf_path_en: "Yusei Fujii - Normal Line of Parabola (EN).pdf",
        cover_image: "Cover - Normal Line of Parabola.png",
        alt_text: "Cover image for the parabola article",
        // SEO metadata
        meta_description_ja: "放物線の法線に関する、直感的でありながら一筋縄ではいかない問題を解説。1問目は、放物線とその法線弦により囲まれた領域に関する最小値を議論する。シンプルな問題設定でありながら、高次関数の増減の評価、相加平均・相乗平均の関係、傘型近似、第一種オイラー積分、積の微分法などの様々な手法が必要になる点が興味深い。2問目は、放物線へ1点から引かれた3本の法線について分析する。この問題は、放物線の縮閉線との関連や、法線の足が原点と同一円周上にあるという性質が美しい。いずれも高校数学の範囲内での解説を試みた。",
        meta_description_en: "This article explains an intuitive yet challenging problem concerning the normals of a parabola. The first problem discusses the minimum value of the area enclosed by a parabola and its normal chord. Despite its simple setup, the problem is intriguing as it requires various techniques, such as evaluating the monotonicity of higher-degree functions, AM-GM inequality, umbrella approximation, Euler's integral of the first kind, and the product rule for differentiation. The second problem analyzes three normals drawn from a single point to a parabola. This problem is fascinating due to its connection with the parabola's evolute and the elegant property that the feet of the normals lie on the same circle as the origin. Both problems are explained within the scope of high school mathematics.",
        keywords_ja: "放物線, 法線, 3本, 最小値, 数学, 幾何学, 縮閉線, 相加平均と相乗平均の関係, 傘型近似, 第一種オイラー積分, 積の微分法",
        keywords_en: "parabola, normal line, three lines, minimum value, mathematics, geometry, evolute, AM-GM inequality, parabolic approximation, Euler integral, product rule",
        og_description_ja: "放物線の法線に関する、直感的でありながら一筋縄ではいかない問題を解説。1問目は、放物線とその法線弦により囲まれた領域に関する最小値を議論する。シンプルな問題設定でありながら、高次関数の増減の評価、相加平均・相乗平均の関係、傘型近似、第一種オイラー積分、積の微分法などの様々な手法が必要になる点が興味深い。2問目は、放物線へ1点から引かれた3本の法線について分析する。この問題は、放物線の縮閉線との関連や、法線の足が原点と同一円周上にあるという性質が美しい。いずれも高校数学の範囲内での解説を試みた。",
        og_description_en: "This article explains an intuitive yet challenging problem concerning the normals of a parabola. The first problem discusses the minimum value of the area enclosed by a parabola and its normal chord. Despite its simple setup, the problem is intriguing as it requires various techniques, such as evaluating the monotonicity of higher-degree functions, AM-GM inequality, umbrella approximation, Euler's integral of the first kind, and the product rule for differentiation. The second problem analyzes three normals drawn from a single point to a parabola. This problem is fascinating due to its connection with the parabola's evolute and the elegant property that the feet of the normals lie on the same circle as the origin. Both problems are explained within the scope of high school mathematics."
    },
    {
        id: "deep-learning-report",
        title_ja: "深層学習に関するレポート",
        title_en: "A Report on Deep Learning",
        author: "Yusei Fujii",
        date: "2025-xx-xx",
        abstract_ja: "Coming Soon...",
        abstract_en: "Coming Soon...",
        type_ja: "レポート",
        type_en: "Report",
        lang_ja: "日本語",
        lang_en: "Japanese",
        pdf_path_ja: "#",
        pdf_path_en: "#",
        cover_image: null,
        alt_text: "Placeholder for cover image",
        // SEO metadata
        meta_description_ja: "深層学習に関する包括的なレポート。最新の研究動向と技術的な洞察を提供します。",
        meta_description_en: "A comprehensive report on deep learning, providing the latest research trends and technical insights.",
        keywords_ja: "深層学習, ディープラーニング, 機械学習, AI, 人工知能, ニューラルネットワーク",
        keywords_en: "deep learning, machine learning, AI, artificial intelligence, neural networks, ML",
        og_description_ja: "深層学習の最新動向を詳しく解説",
        og_description_en: "Detailed explanation of the latest trends in deep learning"
    }
]; 